/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import DAO.ProductDAO;
import DTO.ProductDTO;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author lucas
 */
public class frmMainVIEW extends javax.swing.JFrame {

    /**
     * Creates new form frmMainVIEW
     */
    public frmMainVIEW() {
        initComponents();
        
        listValues();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ProductTable = new javax.swing.JTable();
        BtnAdd_MainView = new javax.swing.JButton();
        BtnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "QTD", "PRICE"
            }
        ));
        jScrollPane1.setViewportView(ProductTable);

        BtnAdd_MainView.setText("ADD");
        BtnAdd_MainView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdd_MainViewActionPerformed(evt);
            }
        });

        BtnUpdate.setText("UPDATE");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BtnAdd_MainView, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnUpdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(BtnAdd_MainView)
                        .addGap(33, 33, 33)
                        .addComponent(BtnUpdate))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAdd_MainViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdd_MainViewActionPerformed
        // TODO add your handling code here:
        FRMAddVIEW FRMAddVIEWObj = new FRMAddVIEW();
        FRMAddVIEWObj.pack();
        FRMAddVIEWObj.setLocationRelativeTo(null);
        FRMAddVIEWObj.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_BtnAdd_MainViewActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        try{
            UpdateField();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "BtnUpdate : " + e);
        }
    }//GEN-LAST:event_BtnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMainVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMainVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMainVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMainVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMainVIEW().setVisible(true);
                
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdd_MainView;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JTable ProductTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
    private void listValues(){
        try {
            ProductDAO objProductDAO= new ProductDAO();
            DefaultTableModel model= (DefaultTableModel) ProductTable.getModel();
            model.setNumRows(0);
            
            ArrayList<ProductDTO> list= objProductDAO.SearchProducts();
            
            for(int num=0;num < list.size();num++){
                model.addRow(new Object[]{
                    list.get(num).getProduct_ID(),
                    list.get(num).getProductName(),
                    list.get(num).getQTDProduct(),
                    list.get(num).getProductPrice()
                });
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "frmMainVIEW: method : listValues :"+e);
        }
    }
    private void UpdateField(){
        int SelectedRow= ProductTable.getSelectedRow();
        if(SelectedRow >=0){
            int Product_ID=(int) ProductTable.getModel().getValueAt(SelectedRow,0);
            String Name=(String) ProductTable.getModel().getValueAt(SelectedRow,1);
            int Product_QTD=(int) ProductTable.getModel().getValueAt(SelectedRow,2);
            Double Product_Price=(Double) ProductTable.getModel().getValueAt(SelectedRow, 3);
            FRMUpdateVIEW ObjFrmUpdateVIEW= new FRMUpdateVIEW(SelectedRow,Product_ID,Name,Product_QTD,Product_Price);
            ObjFrmUpdateVIEW.pack();
            ObjFrmUpdateVIEW.setLocationRelativeTo(null);
            ObjFrmUpdateVIEW.setVisible(true);
            
            
            dispose();
        }
       
    }
    
}
